### ISSUE TITLE
Allow shell into the zabbix container

### ISSUE THREAD

**Issue by Boran** [marc-/docker-zabbix-server#1]
Hi,

You only have one entrypoint, what about allowing "sh" or "bash", so one can "docker exec -i" into the container?

Also, Doc: connect to http://host/zabbix (add the zabbix path).  Perhaps add --restart=always to the containers to they come up after a reboot. The zabbix container should not be created with --rm and should have -d ?

**Comment by marc-** [comment]
Not sure if I get you right, but you can specify entry point with --entrypoint option:

```
docker run --link zabbix-db:db --rm -ti --name zabbix-server -p 80:80 --entrypoint /bin/bash eit8ei8n/zabbix-server
```

Anyways, it should not prevent you from running `docker exec -i` on running container. Keep in mind that this image is based on lightweight Alpine linux and it doesn't has `bash` by default installed.

Regarding to `--rm` option. This image is only front end, all data is persisted in database. So you can remove container without any consequences and start it again. But you still have valid point regarding to `--restart=always` and `-d`.
I agree documentation needs to be updated.

**Comment by marc-** [comment]
I've updated documentation. Assumes this is resolved.
