### ISSUE TITLE
debugging zabbix via the shell

### ISSUE THREAD

**Issue by Boran** [marc-/docker-zabbix-server#2]
Thanks for the quick answer to #1, I was unable to answer sooner from my side.
The two containers start fine for me and the GUI login works.

But zabbix is not polling as I would expect (after I configured some items). Do I'd like to get on the shell of the zabbix container to look at the server logs.

tried "docker exec -i zabbix sh", but it just hangs.
Also tried to create a second "debug" container:

```
docker run --link mysql:db --rm -ti eit8ei8n/zabbix-server --entrypoint sh
mysql root and admin password: FOO
ERROR 1050 (42S01) at line 1: Table 'maintenances' already exists
ERROR 1062 (23000) at line 1: Duplicate entry '1' for key 'PRIMARY'
ERROR 1062 (23000) at line 2: Duplicate entry '10001' for key 'PRIMARY'
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message

(then the tty hangs)
```

The DB errors make sense since there are now two zabbix instances pointing at the same DB.

So what is the suggested method for debugging?

**Comment by marc-** [comment]
Did you try to type any command after `docker exec -i zabbix sh`. It may look like it hangs, but it is actually not. At least it works that way for me. Try to check for zabbix server logs:

``` shell
docker exec -i zabbix cat /var/log/zabbix/zabbix_server.log
```

**Comment by Boran** [comment]
Ah, you are right! One can execute a command as you list, or do "docker exec -i zabbix sh" and then type "ls" and return (for example).
Thanks.
